# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20170430_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
