# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_conversations_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='archive',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
